### ISSUE TITLE
Update to litestar 2.0

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/starlite-feedstock#47]
### Comment:

Currently all branding to `starlite` redirects to `litestar`, e.g.

```yaml
  home: https://litestar.dev
  dev_url: https://github.com/litestar-org/litestar
  doc_url: https://docs.litestar.dev
```

#46 also found that this has started in actual packaging, where the folder inside the repo is now `litestar-1.51.10`.

When 2.0.0 lands, we'll need to update more things.
